# Python & NumPy Warm-up

**Optional pre-tutorial preparation (~30 min)**

If the concepts below feel easy, you're fully ready for the tutorial. If some parts are new, work through them — it'll make the tutorial cells much smoother.

No neural data here — just the tools you'll use repeatedly in both sessions.

## 1. NumPy slicing & broadcasting

NumPy arrays are the backbone of everything we'll do. Let's make sure the indexing feels natural.

In [1]:
import numpy as np

x = np.arange(12).reshape(3, 4)
print("Full array:\n", x)
print("Row 1:   ", x[1, :])       # second row
print("Col 2:   ", x[:, 2])       # third column
print("Every other row:\n", x[::2])

Full array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Row 1:    [4 5 6 7]
Col 2:    [ 2  6 10]
Every other row:
 [[ 0  1  2  3]
 [ 8  9 10 11]]


In [2]:
# Broadcasting: add a different offset to each column
offsets = np.array([10, 20, 30, 40])
print("x + offsets:\n", x + offsets)
# This works because offsets shape (4,) broadcasts against x shape (3, 4)

x + offsets:
 [[10 21 32 43]
 [14 25 36 47]
 [18 29 40 51]]


*If this felt easy, you're ready for section 2.*

## 2. Boolean masking

In the tutorial we'll select spikes by time window and units by quality. Boolean masking does both.

In [3]:
rng = np.random.default_rng(0)
spikes = rng.random(100)        # 100 fake "ISI" values between 0 and 1

# Count how many exceed 0.9 (high-rate bursts)
high = spikes > 0.9
print(f"Spikes > 0.9: {high.sum()} out of {len(spikes)}")
print("Their values:", spikes[high])

Spikes > 0.9: 16 out of 100
Their values: [0.91275558 0.93507242 0.99720994 0.98083534 0.93404352 0.94211311
 0.92715455 0.95459049 0.99509651 0.94894367 0.93205969 0.92742393
 0.96792619 0.98119504 0.95721018 0.97262881]


In [4]:
# Combine two conditions
orientations = np.tile([0, 45, 90, 135, 180, 225, 270, 315], 20)[:100]
rates = rng.exponential(5, size=100)

# Select trials where orientation is 0° and rate is above average
mask = (orientations == 0) & (rates > rates.mean())
print(f"Trials at 0° with above-mean rate: {mask.sum()}")
print("Rates:", rates[mask].round(1))

Trials at 0° with above-mean rate: 6
Rates: [10.9 19.7  6.   9.8 11.6  6.3]


*If this felt easy, you're ready for section 3.*

## 3. Matplotlib: raster and line plots

Two plot types come up constantly: rasters (discrete spike events) and line plots (rates, PSTHs).

In [5]:
import matplotlib
matplotlib.use("Agg")   # headless rendering; remove this line when running in Colab/Jupyter
import matplotlib.pyplot as plt

# Raster: 5 fake neurons with Poisson-like spike trains
fig, ax = plt.subplots(figsize=(7, 3))
spike_trains = [np.sort(rng.uniform(0, 2, rng.integers(10, 30))) for _ in range(5)]
ax.eventplot(spike_trains, lineoffsets=range(5), linelengths=0.7, colors="black")
ax.set_xlabel("Time (s)"); ax.set_ylabel("Neuron")
ax.set_title("Spike raster — 5 neurons, 2 seconds")
plt.tight_layout(); plt.savefig("/tmp/warmup_raster.png"); plt.close()
print("Raster saved.")

Raster saved.


In [6]:
# Line plot: PSTH (peri-stimulus time histogram)
t = np.linspace(-0.5, 1.5, 80)
rate = 5 + 15 * np.exp(-((t - 0.3) ** 2) / (2 * 0.1 ** 2))   # Gaussian bump at 0.3 s

fig, ax = plt.subplots(figsize=(6, 3))
ax.plot(t, rate, label="unit 42")
ax.axvline(0, color="gray", lw=0.8, ls="--", label="stimulus onset")
ax.set_xlabel("Time from stimulus onset (s)")
ax.set_ylabel("Firing rate (Hz)")
ax.legend(); ax.set_title("PSTH")
plt.tight_layout(); plt.savefig("/tmp/warmup_psth.png"); plt.close()
print("PSTH saved.")

PSTH saved.


*If this felt easy, you're ready for section 4.*

## 4. PCA on a toy population

In Session 2 we'll run PCA on real motor cortex data. Here's the same pipeline on 2D Gaussian blobs.

In [7]:
from sklearn.decomposition import PCA

# 200 samples from a correlated 2D Gaussian (elliptical blob)
cov = np.array([[4.0, 1.8], [1.8, 1.0]])
X = rng.multivariate_normal([0, 0], cov, size=200)

pca = PCA(n_components=2).fit(X)
print("Explained variance ratio:", pca.explained_variance_ratio_.round(3))
print("PC1 direction:", pca.components_[0].round(3))

Z = pca.transform(X)   # project to PC space

fig, axes = plt.subplots(1, 2, figsize=(9, 3))
axes[0].scatter(X[:, 0], X[:, 1], s=10, alpha=0.5)
axes[0].set_title("Original space"); axes[0].set_xlabel("x1"); axes[0].set_ylabel("x2")
axes[0].set_aspect("equal")
axes[1].scatter(Z[:, 0], Z[:, 1], s=10, alpha=0.5, color="C1")
axes[1].set_title("PC space"); axes[1].set_xlabel("PC1"); axes[1].set_ylabel("PC2")
axes[1].set_aspect("equal")
plt.tight_layout(); plt.savefig("/tmp/warmup_pca.png"); plt.close()
print("PCA plot saved.")

Explained variance ratio: [0.965 0.035]
PC1 direction: [0.905 0.425]
PCA plot saved.


*If this felt easy, you're fully ready for both sessions!*

---

**Quick reference:**
- NumPy docs: https://numpy.org/doc/stable/
- Matplotlib tutorials: https://matplotlib.org/stable/tutorials/index.html
- scikit-learn PCA: https://scikit-learn.org/stable/modules/decomposition.html#pca